import { z } from "zod";
import { mutationResponseOptionsSchema } from "../operation-plan";
import type { TrickroomMcpProjectRef } from "../project-resolver";

export const jsonPrimitiveSchema = z.union([
	z.string(),
	z.number(),
	z.boolean(),
	z.null(),
]);

export const rejectedPersistentIdSchema = z
	.never()
	.optional()
	.describe(
		"Persistent element IDs are generated by the server and must not be supplied.",
	);

export const systemComponentManifestRevisionSchema = z
	.string()
	.startsWith("sha256:")
	.describe("Current system component manifest revision from list/describe.");

export const projectRefSchema: z.ZodType<TrickroomMcpProjectRef | undefined> = z
	.object({
		locationId: z
			.string()
			.min(1)
			.optional()
			.describe("Registered local Trickroom project location ID."),
		projectId: z
			.string()
			.min(1)
			.optional()
			.describe(
				"Stable Trickroom project ID. Ambiguous registered IDs require locationId.",
			),
	})
	.strict()
	.optional()
	.describe(
		"Optional explicit project selector. Prefer locationId for automation; omit to use the MCP session default.",
	);

export const projectScopedInputSchema = {
	project: projectRefSchema,
} as const;

export const mutationResponseInputSchema = mutationResponseOptionsSchema
	.optional()
	.describe(
		'Response verbosity controls. Default: error issues, warningCount, and likely-typo (UNKNOWN_TAILWIND_UTILITY, UNKNOWN_*_TOKEN) and MISSING_RENDERER warnings on the elements this write touched. includeWarnings:true returns every warning in scope, includeWarnings:false none; warningScope:"file" widens the scope to the whole design; includeTokenDiagnostics adds the custom-utility catalog.',
	);

export const mutationScopedInputSchema = {
	...projectScopedInputSchema,
	response: mutationResponseInputSchema,
};

export const withMutationScopedInput = <Shape extends z.ZodRawShape>(
	shape: Shape,
) => ({
	...shape,
	...mutationScopedInputSchema,
});

export const withProjectScopedInput = <Shape extends z.ZodRawShape>(
	shape: Shape,
) => ({
	...shape,
	...projectScopedInputSchema,
});

export const mcpReadResponseFormatSchema = z
	.enum(["json", "summary"])
	.optional()
	.describe(
		'Response text format. "json" returns structured JSON in text (default). "summary" returns a short prose summary.',
	);
