import { z } from "zod";
import type { TrickroomMcpProjectRef } from "../project-resolver";
import { TOOL } from "../tool-names";

// Leaf module: operation-plan.ts, design-operations.ts and subtree-schemas.ts
// import from here, so keep runtime imports out of it.

export const jsonPrimitiveSchema = z.union([
	z.string(),
	z.number(),
	z.boolean(),
	z.null(),
]);

export const rejectedPersistentIdSchema = z
	.never()
	.optional()
	.describe(
		"Persistent element IDs are generated by the server and must not be supplied.",
	);

const designFileUuidPattern =
	/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export const isDesignFileId = (value: string) =>
	designFileUuidPattern.test(value);

/**
 * Design file id. Published as a plain described string: the uuid check is a
 * refinement, so it validates every call without putting zod's long uuid
 * regex into each tool's JSON schema. Override the description with
 * `.describe()` where the role differs (source/target, optional).
 */
export const designFileIdSchema = z
	.string()
	.refine(isDesignFileId, {
		message: `expected a design file UUID from ${TOOL.designList}`,
	})
	.describe("Design file UUID.");

/**
 * Optimistic-concurrency token for design files, memory and system component
 * manifests. Opaque: compare and pass back, never parse. Design revisions are
 * becoming composite tokens once boards split into their own files.
 */
export const expectedRevisionSchema = z
	.string()
	.min(1)
	.describe("Pass back the revision from your last read.");

export const projectRefSchema: z.ZodType<TrickroomMcpProjectRef | undefined> = z
	.object({
		locationId: z.string().min(1).optional(),
		projectId: z.string().min(1).optional(),
	})
	.strict()
	.optional()
	.describe(
		"Project override ({ locationId }); defaults to the selected project.",
	);

export const projectScopedInputSchema = {
	project: projectRefSchema,
} as const;

/**
 * Write and validation response detail. "compact" (the default) returns error
 * issues, warningCount and grouped likely-typo warnings on touched elements;
 * "full" adds every warning on them, token diagnostics, per-step details and
 * full id maps.
 */
export const mutationResponseDetailSchema = z.enum(["compact", "full"]);

export type MutationResponseDetail = z.infer<
	typeof mutationResponseDetailSchema
>;

export const mutationResponseInputSchema = mutationResponseDetailSchema
	.optional()
	.describe(
		'"full" adds all warnings, token diagnostics and full step/id details.',
	);

export const mutationScopedInputSchema = {
	...projectScopedInputSchema,
	response: mutationResponseInputSchema,
};

export const withMutationScopedInput = <Shape extends z.ZodRawShape>(
	shape: Shape,
) => ({
	...shape,
	...mutationScopedInputSchema,
});

export const withProjectScopedInput = <Shape extends z.ZodRawShape>(
	shape: Shape,
) => ({
	...shape,
	...projectScopedInputSchema,
});
