import { z } from "zod";
import type { TrickroomMcpProjectRef } from "../project-resolver";

// Leaf module: operation-plan.ts, design-operations.ts and subtree-schemas.ts
// import from here, so keep runtime imports out of it.

export const jsonPrimitiveSchema = z.union([
	z.string(),
	z.number(),
	z.boolean(),
	z.null(),
]);

export const rejectedPersistentIdSchema = z
	.never()
	.optional()
	.describe(
		"Persistent element IDs are generated by the server and must not be supplied.",
	);

const designFileUuidPattern =
	/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export const isDesignFileId = (value: string) =>
	designFileUuidPattern.test(value);

/**
 * Design file id. Published as a plain described string: the uuid check is a
 * refinement, so it validates every call without putting zod's long uuid
 * regex into each tool's JSON schema. Override the description with
 * `.describe()` where the role differs (source/target, optional).
 */
export const designFileIdSchema = z
	.string()
	.refine(isDesignFileId, {
		message: "expected a design file UUID from listDesignFiles",
	})
	.describe("Design file UUID.");

/**
 * Optimistic-concurrency token for design files, memory and system component
 * manifests. Opaque: compare and pass back, never parse. Design revisions are
 * becoming composite tokens once boards split into their own files.
 */
export const expectedRevisionSchema = z
	.string()
	.min(1)
	.describe("Pass back the revision from your last read.");

export const projectRefSchema: z.ZodType<TrickroomMcpProjectRef | undefined> = z
	.object({
		locationId: z
			.string()
			.min(1)
			.optional()
			.describe("Registered local Trickroom project location ID."),
		projectId: z
			.string()
			.min(1)
			.optional()
			.describe(
				"Stable Trickroom project ID. Ambiguous registered IDs require locationId.",
			),
	})
	.strict()
	.optional()
	.describe(
		"Optional explicit project selector. Prefer locationId for automation; omit to use the MCP session default.",
	);

export const projectScopedInputSchema = {
	project: projectRefSchema,
} as const;

export const mutationResponseOptionsSchema = z
	.object({
		includeWarnings: z.boolean().optional(),
		warningScope: z.enum(["affected", "file"]).optional(),
		includeTokenDiagnostics: z.boolean().optional(),
		includeStepDetails: z
			.boolean()
			.optional()
			.describe(
				"applyDesignOperations only: return full per-step summaries and aggregate changed/inserted id lists instead of the compact per-step result.",
			),
	})
	.strict();

export const mutationResponseInputSchema = mutationResponseOptionsSchema
	.optional()
	.describe(
		'Response verbosity controls. Default: error issues, warningCount, and likely-typo (UNKNOWN_TAILWIND_UTILITY, UNKNOWN_*_TOKEN) and MISSING_RENDERER warnings on the elements this write touched. includeWarnings:true returns every warning in scope, includeWarnings:false none; warningScope:"file" widens the scope to the whole design; includeTokenDiagnostics adds the custom-utility catalog.',
	);

export const mutationScopedInputSchema = {
	...projectScopedInputSchema,
	response: mutationResponseInputSchema,
};

export const withMutationScopedInput = <Shape extends z.ZodRawShape>(
	shape: Shape,
) => ({
	...shape,
	...mutationScopedInputSchema,
});

export const withProjectScopedInput = <Shape extends z.ZodRawShape>(
	shape: Shape,
) => ({
	...shape,
	...projectScopedInputSchema,
});

export const mcpReadResponseFormatSchema = z
	.enum(["json", "summary"])
	.optional()
	.describe(
		'Response text format. "json" returns structured JSON in text (default). "summary" returns a short prose summary.',
	);
