import type { RecipeRegistry } from "../../types";
import { assetIdProp } from "../../utils/resource-props";
import type { BaseUiRecipes } from "./components";

const recipes = {
	"accordion.default": {
		id: "base-ui/accordion.default",
		label: "Accordion",
		description: "Accordion root with item slot.",
		version: 1,
		root: {
			path: "root",
			library: "base-ui",
			component: "accordion.root",
			slot: "items",
			children: [],
		},
		slots: {
			items: {
				name: "items",
				label: "Items",
				hostPath: "root",
				allowedChildren: [
					{ library: "base-ui", component: "accordion.item" },
					{
						kind: "recipe",
						library: "base-ui",
						recipe: "accordion.item.default",
					},
				],
			},
		},
		controls: {
			orientation: {
				label: "Orientation",
				input: "radio",
				prop: "orientation",
				valueType: "string",
				options: [
					{ label: "Vertical", value: "vertical" },
					{ label: "Horizontal", value: "horizontal" },
				],
				defaultValue: "vertical",
				path: "root",
			},
			disabled: {
				label: "Disabled",
				input: "switch",
				prop: "disabled",
				valueType: "boolean",
				defaultValue: false,
				path: "root",
			},
		},
	},
	"accordion.item.default": {
		id: "base-ui/accordion.item.default",
		label: "Accordion Item",
		description: "Accordion item with trigger and panel slots.",
		version: 1,
		root: {
			path: "root",
			library: "base-ui",
			component: "accordion.item",
			children: [
				{
					path: "header",
					library: "base-ui",
					component: "accordion.header",
					children: [
						{
							path: "trigger",
							library: "base-ui",
							component: "accordion.trigger",
							slot: "trigger",
							children: [],
						},
					],
				},
				{
					path: "panel",
					library: "base-ui",
					component: "accordion.panel",
					slot: "panel",
					children: [],
				},
			],
		},
		slots: {
			trigger: {
				name: "trigger",
				label: "Trigger",
				hostPath: "trigger",
				allowedChildren: undefined,
			},
			panel: {
				name: "panel",
				label: "Panel",
				hostPath: "panel",
				allowedChildren: undefined,
			},
		},
		controls: {
			disabled: {
				label: "Disabled",
				input: "switch",
				prop: "disabled",
				valueType: "boolean",
				defaultValue: false,
				path: "root",
			},
		},
	},
	"avatar.default": {
		id: "base-ui/avatar.default",
		label: "Avatar",
		description: "Avatar composition with image and fallback slot.",
		version: 1,
		root: {
			path: "root",
			library: "base-ui",
			component: "avatar.root",
			children: [
				{
					path: "image",
					library: "base-ui",
					component: "avatar.image",
					props: {
						[assetIdProp]: "",
						alt: "",
					},
				},
				{
					path: "fallback",
					library: "base-ui",
					component: "avatar.fallback",
					slot: "fallback",
					children: [],
				},
			],
		},
		slots: {
			fallback: {
				name: "fallback",
				label: "Fallback",
				hostPath: "fallback",
				allowedChildren: undefined,
			},
		},
	},
	"collapsible.default": {
		id: "base-ui/collapsible.default",
		label: "Collapsible",
		description: "Collapsible composition with trigger and panel slots.",
		version: 1,
		root: {
			path: "root",
			library: "base-ui",
			component: "collapsible.root",
			children: [
				{
					path: "trigger",
					library: "base-ui",
					component: "collapsible.trigger",
					slot: "trigger",
					children: [],
				},
				{
					path: "panel",
					library: "base-ui",
					component: "collapsible.panel",
					slot: "panel",
					children: [],
				},
			],
		},
		slots: {
			trigger: {
				name: "trigger",
				label: "Trigger",
				hostPath: "trigger",
				allowedChildren: undefined,
			},
			panel: {
				name: "panel",
				label: "Panel",
				hostPath: "panel",
				allowedChildren: undefined,
			},
		},
		controls: {
			defaultOpen: {
				label: "Default open",
				input: "switch",
				prop: "defaultOpen",
				valueType: "boolean",
				defaultValue: false,
				path: "root",
			},
			disabled: {
				label: "Disabled",
				input: "switch",
				prop: "disabled",
				valueType: "boolean",
				defaultValue: false,
				path: "root",
			},
			keepMounted: {
				label: "Keep mounted",
				input: "switch",
				prop: "keepMounted",
				valueType: "boolean",
				defaultValue: false,
				path: "panel",
			},
		},
	},
	"menu.default": {
		id: "base-ui/menu.default",
		label: "Menu",
		description: "Menu composition with trigger and item slots.",
		version: 1,
		root: {
			path: "root",
			library: "base-ui",
			component: "menu.root",
			children: [
				{
					path: "trigger",
					library: "base-ui",
					component: "menu.trigger",
					slot: "trigger",
					children: [],
				},
				{
					path: "portal",
					library: "base-ui",
					component: "menu.portal",
					children: [
						{
							path: "positioner",
							library: "base-ui",
							component: "menu.positioner",
							children: [
								{
									path: "popup",
									library: "base-ui",
									component: "menu.popup",
									slot: "items",
									children: [],
								},
							],
						},
					],
				},
			],
		},
		slots: {
			trigger: {
				name: "trigger",
				label: "Trigger",
				hostPath: "trigger",
				allowedChildren: undefined,
			},
			items: {
				name: "items",
				label: "Items",
				hostPath: "popup",
				allowedChildren: [
					{ library: "base-ui", component: "menu.item" },
					{ library: "base-ui", component: "menu.separator" },
				],
			},
		},
		controls: {
			orientation: {
				label: "Orientation",
				input: "radio",
				prop: "orientation",
				valueType: "string",
				options: [
					{ label: "Vertical", value: "vertical" },
					{ label: "Horizontal", value: "horizontal" },
				],
				defaultValue: "vertical",
				path: "root",
			},
			loopFocus: {
				label: "Loop focus",
				input: "switch",
				prop: "loopFocus",
				valueType: "boolean",
				defaultValue: true,
				path: "root",
			},
			modal: {
				label: "Modal",
				input: "switch",
				prop: "modal",
				valueType: "boolean",
				defaultValue: true,
				path: "root",
			},
			openOnHover: {
				label: "Open on hover",
				input: "switch",
				prop: "openOnHover",
				valueType: "boolean",
				defaultValue: false,
				path: "trigger",
			},
			side: {
				label: "Side",
				input: "select",
				prop: "side",
				valueType: "string",
				options: [
					{ label: "Top", value: "top" },
					{ label: "Right", value: "right" },
					{ label: "Bottom", value: "bottom" },
					{ label: "Left", value: "left" },
				],
				defaultValue: "bottom",
				path: "positioner",
			},
			align: {
				label: "Align",
				input: "select",
				prop: "align",
				valueType: "string",
				options: [
					{ label: "Start", value: "start" },
					{ label: "Center", value: "center" },
					{ label: "End", value: "end" },
				],
				defaultValue: "start",
				path: "positioner",
			},
			sideOffset: {
				label: "Side offset",
				input: "number",
				prop: "sideOffset",
				valueType: "number",
				defaultValue: 4,
				path: "positioner",
			},
		},
	},
	"radio-group.default": {
		id: "base-ui/radio-group.default",
		label: "Radio Group",
		description: "Radio group with radio item slot.",
		version: 1,
		root: {
			path: "root",
			library: "base-ui",
			component: "radio-group",
			slot: "items",
			children: [],
		},
		slots: {
			items: {
				name: "items",
				label: "Items",
				hostPath: "root",
				allowedChildren: [
					{ library: "base-ui", component: "radio.root" },
					{
						kind: "recipe",
						library: "base-ui",
						recipe: "radio.default",
					},
				],
			},
		},
		controls: {
			name: {
				label: "Name",
				input: "text",
				prop: "name",
				valueType: "string",
				defaultValue: "",
				path: "root",
			},
			defaultValue: {
				label: "Default value",
				input: "text",
				prop: "defaultValue",
				valueType: "string",
				defaultValue: "",
				path: "root",
			},
			disabled: {
				label: "Disabled",
				input: "switch",
				prop: "disabled",
				valueType: "boolean",
				defaultValue: false,
				path: "root",
			},
			readOnly: {
				label: "Read only",
				input: "switch",
				prop: "readOnly",
				valueType: "boolean",
				defaultValue: false,
				path: "root",
			},
			required: {
				label: "Required",
				input: "switch",
				prop: "required",
				valueType: "boolean",
				defaultValue: false,
				path: "root",
			},
		},
	},
	"radio.default": {
		id: "base-ui/radio.default",
		label: "Radio",
		description: "Radio item with indicator slot.",
		version: 1,
		root: {
			path: "root",
			library: "base-ui",
			component: "radio.root",
			props: {
				value: "option",
			},
			children: [
				{
					path: "indicator",
					library: "base-ui",
					component: "radio.indicator",
					slot: "indicator",
					children: [],
				},
			],
		},
		slots: {
			indicator: {
				name: "indicator",
				label: "Indicator",
				hostPath: "indicator",
				allowedChildren: undefined,
			},
		},
		controls: {
			value: {
				label: "Value",
				input: "text",
				prop: "value",
				valueType: "string",
				defaultValue: "option",
				path: "root",
			},
			disabled: {
				label: "Disabled",
				input: "switch",
				prop: "disabled",
				valueType: "boolean",
				defaultValue: false,
				path: "root",
			},
			readOnly: {
				label: "Read only",
				input: "switch",
				prop: "readOnly",
				valueType: "boolean",
				defaultValue: false,
				path: "root",
			},
			required: {
				label: "Required",
				input: "switch",
				prop: "required",
				valueType: "boolean",
				defaultValue: false,
				path: "root",
			},
			keepMounted: {
				label: "Keep mounted",
				input: "switch",
				prop: "keepMounted",
				valueType: "boolean",
				defaultValue: false,
				path: "indicator",
			},
		},
	},
	"switch.default": {
		id: "base-ui/switch.default",
		label: "Switch",
		description: "Switch with thumb slot.",
		version: 1,
		root: {
			path: "root",
			library: "base-ui",
			component: "switch.root",
			children: [
				{
					path: "thumb",
					library: "base-ui",
					component: "switch.thumb",
					slot: "thumb",
					children: [],
				},
			],
		},
		slots: {
			thumb: {
				name: "thumb",
				label: "Thumb",
				hostPath: "thumb",
				allowedChildren: undefined,
			},
		},
		controls: {
			name: {
				label: "Name",
				input: "text",
				prop: "name",
				valueType: "string",
				defaultValue: "",
				path: "root",
			},
			defaultChecked: {
				label: "Default checked",
				input: "switch",
				prop: "defaultChecked",
				valueType: "boolean",
				defaultValue: false,
				path: "root",
			},
			disabled: {
				label: "Disabled",
				input: "switch",
				prop: "disabled",
				valueType: "boolean",
				defaultValue: false,
				path: "root",
			},
			readOnly: {
				label: "Read only",
				input: "switch",
				prop: "readOnly",
				valueType: "boolean",
				defaultValue: false,
				path: "root",
			},
			required: {
				label: "Required",
				input: "switch",
				prop: "required",
				valueType: "boolean",
				defaultValue: false,
				path: "root",
			},
		},
	},
	"toggle-group.default": {
		id: "base-ui/toggle-group.default",
		label: "Toggle Group",
		description: "Toggle group with toggle item slot.",
		version: 1,
		root: {
			path: "root",
			library: "base-ui",
			component: "toggle-group",
			slot: "items",
			children: [],
		},
		slots: {
			items: {
				name: "items",
				label: "Items",
				hostPath: "root",
				allowedChildren: [{ library: "base-ui", component: "toggle" }],
			},
		},
		controls: {
			orientation: {
				label: "Orientation",
				input: "radio",
				prop: "orientation",
				valueType: "string",
				options: [
					{ label: "Horizontal", value: "horizontal" },
					{ label: "Vertical", value: "vertical" },
				],
				defaultValue: "horizontal",
				path: "root",
			},
			multiple: {
				label: "Multiple",
				input: "switch",
				prop: "multiple",
				valueType: "boolean",
				defaultValue: false,
				path: "root",
			},
			loopFocus: {
				label: "Loop focus",
				input: "switch",
				prop: "loopFocus",
				valueType: "boolean",
				defaultValue: true,
				path: "root",
			},
			disabled: {
				label: "Disabled",
				input: "switch",
				prop: "disabled",
				valueType: "boolean",
				defaultValue: false,
				path: "root",
			},
		},
	},
} satisfies RecipeRegistry<BaseUiRecipes>;

export default recipes;
