import type { ElementType } from "react";
import {
	AccordionHeader,
	AccordionItem,
	AccordionPanel,
	AccordionRoot,
	AccordionTrigger,
} from "./accordion";
import { AvatarFallback, AvatarImage, AvatarRoot } from "./avatar";
import { Button } from "./button";
import { CheckboxGroup, CheckboxIndicator, CheckboxRoot } from "./checkbox";
import {
	CollapsiblePanel,
	CollapsibleRoot,
	CollapsibleTrigger,
} from "./collapsible";
import {
	ComboboxArrow,
	ComboboxBackdrop,
	ComboboxChip,
	ComboboxChipRemove,
	ComboboxChips,
	ComboboxClear,
	ComboboxEmpty,
	ComboboxGroup,
	ComboboxGroupLabel,
	ComboboxIcon,
	ComboboxInput,
	ComboboxInputGroup,
	ComboboxItem,
	ComboboxItemIndicator,
	ComboboxLabel,
	ComboboxList,
	ComboboxPopup,
	ComboboxPortal,
	ComboboxPositioner,
	ComboboxRoot,
	ComboboxRow,
	ComboboxSeparator,
	ComboboxStatus,
	ComboboxTrigger,
	ComboboxValue,
} from "./combobox";
import type { BaseUiComponents } from "./components";
import {
	DrawerBackdrop,
	DrawerClose,
	DrawerContent,
	DrawerDescription,
	DrawerIndent,
	DrawerIndentBackground,
	DrawerPopup,
	DrawerPortal,
	DrawerProvider,
	DrawerRoot,
	DrawerSwipeArea,
	DrawerTitle,
	DrawerTrigger,
	DrawerViewport,
} from "./drawer";
import {
	FieldControl,
	FieldDescription,
	FieldError,
	FieldItem,
	FieldLabel,
	FieldRoot,
} from "./field";
import { FieldsetLegend, FieldsetRoot } from "./fieldset";
import { Form } from "./form";
import { Input } from "./input";
import {
	MenuItem,
	MenuPopup,
	MenuPortal,
	MenuPositioner,
	MenuRoot,
	MenuSeparator,
	MenuTrigger,
} from "./menu";
import {
	MeterIndicator,
	MeterLabel,
	MeterRoot,
	MeterTrack,
	MeterValue,
} from "./meter";
import { RadioGroup, RadioIndicator, RadioRoot } from "./radio";
import {
	ScrollAreaContent,
	ScrollAreaCorner,
	ScrollAreaRoot,
	ScrollAreaScrollbar,
	ScrollAreaThumb,
	ScrollAreaViewport,
} from "./scroll-area";
import {
	SelectArrow,
	SelectBackdrop,
	SelectGroup,
	SelectGroupLabel,
	SelectIcon,
	SelectItem,
	SelectItemIndicator,
	SelectItemText,
	SelectLabel,
	SelectList,
	SelectPopup,
	SelectPortal,
	SelectPositioner,
	SelectRoot,
	SelectScrollDownArrow,
	SelectScrollUpArrow,
	SelectSeparator,
	SelectTrigger,
	SelectValue,
} from "./select";
import { Separator } from "./separator";
import {
	SliderControl,
	SliderIndicator,
	SliderLabel,
	SliderRoot,
	SliderThumb,
	SliderTrack,
	SliderValue,
} from "./slider";
import { SwitchRoot, SwitchThumb } from "./switch";
import { TabsIndicator, TabsList, TabsPanel, TabsRoot, TabsTab } from "./tabs";
import { Toggle, ToggleGroup } from "./toggle";
import {
	TooltipArrow,
	TooltipPopup,
	TooltipPortal,
	TooltipPositioner,
	TooltipProvider,
	TooltipRoot,
	TooltipTrigger,
} from "./tooltip";

export const baseUiRenderComponents = {
	"accordion.root": AccordionRoot,
	"accordion.item": AccordionItem,
	"accordion.header": AccordionHeader,
	"accordion.trigger": AccordionTrigger,
	"accordion.panel": AccordionPanel,
	"avatar.root": AvatarRoot,
	"avatar.image": AvatarImage,
	"avatar.fallback": AvatarFallback,
	button: Button,
	"checkbox.root": CheckboxRoot,
	"checkbox.indicator": CheckboxIndicator,
	"checkbox-group": CheckboxGroup,
	"collapsible.root": CollapsibleRoot,
	"collapsible.trigger": CollapsibleTrigger,
	"collapsible.panel": CollapsiblePanel,
	"combobox.root": ComboboxRoot,
	"combobox.label": ComboboxLabel,
	"combobox.value": ComboboxValue,
	"combobox.input": ComboboxInput,
	"combobox.input-group": ComboboxInputGroup,
	"combobox.trigger": ComboboxTrigger,
	"combobox.list": ComboboxList,
	"combobox.status": ComboboxStatus,
	"combobox.portal": ComboboxPortal,
	"combobox.backdrop": ComboboxBackdrop,
	"combobox.positioner": ComboboxPositioner,
	"combobox.popup": ComboboxPopup,
	"combobox.arrow": ComboboxArrow,
	"combobox.icon": ComboboxIcon,
	"combobox.group": ComboboxGroup,
	"combobox.group-label": ComboboxGroupLabel,
	"combobox.item": ComboboxItem,
	"combobox.item-indicator": ComboboxItemIndicator,
	"combobox.chips": ComboboxChips,
	"combobox.chip": ComboboxChip,
	"combobox.chip-remove": ComboboxChipRemove,
	"combobox.row": ComboboxRow,
	"combobox.empty": ComboboxEmpty,
	"combobox.clear": ComboboxClear,
	"combobox.separator": ComboboxSeparator,
	"drawer.provider": DrawerProvider,
	"drawer.root": DrawerRoot,
	"drawer.trigger": DrawerTrigger,
	"drawer.portal": DrawerPortal,
	"drawer.backdrop": DrawerBackdrop,
	"drawer.viewport": DrawerViewport,
	"drawer.popup": DrawerPopup,
	"drawer.content": DrawerContent,
	"drawer.title": DrawerTitle,
	"drawer.description": DrawerDescription,
	"drawer.close": DrawerClose,
	"drawer.swipe-area": DrawerSwipeArea,
	"drawer.indent": DrawerIndent,
	"drawer.indent-background": DrawerIndentBackground,
	"field.root": FieldRoot,
	"field.label": FieldLabel,
	"field.control": FieldControl,
	"field.description": FieldDescription,
	"field.item": FieldItem,
	"field.error": FieldError,
	"fieldset.root": FieldsetRoot,
	"fieldset.legend": FieldsetLegend,
	form: Form,
	input: Input,
	"meter.root": MeterRoot,
	"meter.label": MeterLabel,
	"meter.track": MeterTrack,
	"meter.indicator": MeterIndicator,
	"meter.value": MeterValue,
	"menu.root": MenuRoot,
	"menu.trigger": MenuTrigger,
	"menu.portal": MenuPortal,
	"menu.positioner": MenuPositioner,
	"menu.popup": MenuPopup,
	"menu.item": MenuItem,
	"menu.separator": MenuSeparator,
	"radio-group": RadioGroup,
	"radio.root": RadioRoot,
	"radio.indicator": RadioIndicator,
	"scroll-area.root": ScrollAreaRoot,
	"scroll-area.viewport": ScrollAreaViewport,
	"scroll-area.content": ScrollAreaContent,
	"scroll-area.scrollbar": ScrollAreaScrollbar,
	"scroll-area.thumb": ScrollAreaThumb,
	"scroll-area.corner": ScrollAreaCorner,
	separator: Separator,
	"select.root": SelectRoot,
	"select.label": SelectLabel,
	"select.trigger": SelectTrigger,
	"select.value": SelectValue,
	"select.icon": SelectIcon,
	"select.portal": SelectPortal,
	"select.backdrop": SelectBackdrop,
	"select.positioner": SelectPositioner,
	"select.popup": SelectPopup,
	"select.list": SelectList,
	"select.item": SelectItem,
	"select.item-indicator": SelectItemIndicator,
	"select.item-text": SelectItemText,
	"select.arrow": SelectArrow,
	"select.scroll-down-arrow": SelectScrollDownArrow,
	"select.scroll-up-arrow": SelectScrollUpArrow,
	"select.group": SelectGroup,
	"select.group-label": SelectGroupLabel,
	"select.separator": SelectSeparator,
	"slider.root": SliderRoot,
	"slider.label": SliderLabel,
	"slider.value": SliderValue,
	"slider.control": SliderControl,
	"slider.track": SliderTrack,
	"slider.thumb": SliderThumb,
	"slider.indicator": SliderIndicator,
	"switch.root": SwitchRoot,
	"switch.thumb": SwitchThumb,
	"tabs.root": TabsRoot,
	"tabs.list": TabsList,
	"tabs.tab": TabsTab,
	"tabs.indicator": TabsIndicator,
	"tabs.panel": TabsPanel,
	"tooltip.provider": TooltipProvider,
	"tooltip.root": TooltipRoot,
	"tooltip.trigger": TooltipTrigger,
	"tooltip.portal": TooltipPortal,
	"tooltip.positioner": TooltipPositioner,
	"tooltip.popup": TooltipPopup,
	"tooltip.arrow": TooltipArrow,
	toggle: Toggle,
	"toggle-group": ToggleGroup,
} satisfies Record<BaseUiComponents, ElementType>;
