import { z } from "zod";
import { isJsonPrimitive } from "../libraries/registry";
import type {
	ProposedElementNode,
	ProposedRecipeNode,
	ProposedSubtreeNode,
	ValidateSubtreeOptions,
} from "../services/design-transform-service";

const jsonPrimitiveSchema = z.union([
	z.string(),
	z.number(),
	z.boolean(),
	z.null(),
]);

const rejectedPersistentIdSchema = z
	.never()
	.optional()
	.describe(
		"Persistent element IDs are generated by the server and must not be supplied.",
	);

export const proposedRecipeNodeSchema: z.ZodType<ProposedRecipeNode> = z
	.object({
		id: rejectedPersistentIdSchema,
		kind: z.literal("recipe"),
		tempId: z.string().min(1).optional(),
		library: z.string().min(1),
		recipe: z.string().min(1),
		children: z.never().optional(),
		props: z.never().optional(),
		name: z.never().optional(),
		className: z.never().optional(),
		text: z.never().optional(),
	})
	.strict();

export const proposedElementNodeSchema: z.ZodType<ProposedElementNode> = z
	.object({
		id: rejectedPersistentIdSchema,
		kind: z.literal("element").optional(),
		tempId: z.string().min(1).optional(),
		library: z.string().min(1),
		component: z.string().min(1),
		name: z.string().optional(),
		className: z.string().optional(),
		props: z.record(z.string(), jsonPrimitiveSchema).optional(),
		text: z.string().optional(),
		children: z.array(z.lazy(() => proposedSubtreeNodeSchema)).optional(),
	})
	.strict();

export const proposedSubtreeNodeSchema: z.ZodType<ProposedSubtreeNode> = z.lazy(
	() =>
		z.union([
			proposedRecipeNodeSchema,
			proposedElementNodeSchema,
		]) as z.ZodType<ProposedSubtreeNode>,
);

export const validateSubtreeOptionsSchema: z.ZodType<ValidateSubtreeOptions> = z
	.object({
		maxNodes: z.number().int().min(1).optional(),
		maxDepth: z.number().int().min(1).optional(),
		includeNormalizedTree: z.boolean().optional(),
		allowRecipes: z.boolean().optional(),
	})
	.strict();

export const addSubtreeOptionsSchema: z.ZodType<
	Omit<ValidateSubtreeOptions, "includeNormalizedTree">
> = z
	.object({
		maxNodes: z.number().int().min(1).optional(),
		maxDepth: z.number().int().min(1).optional(),
		allowRecipes: z.boolean().optional(),
	})
	.strict();

export const validateCopySubtreeOptionsSchema = z
	.object({
		maxNodes: z.number().int().min(1).optional(),
		maxDepth: z.number().int().min(1).optional(),
	})
	.strict();

export const isSubtreeJsonPrimitive = isJsonPrimitive;
