import { sha256Hex } from "../utils/sha256";
import {
	collectDesignOnlyPaths,
	stripDesignOnlyNodes,
} from "../utils/system-component-design-only";
import { stableStringify } from "../utils/system-component-template-hash";
import type { SystemComponentDraftPayload } from "../utils/system-components";

export type CodegenSource = "published" | "draft";

export type CodegenHeader = {
	version: 1;
	systemId: string;
	componentId: string;
	slug: string;
	source: CodegenSource;
	publishedVersion: string | null;
	templateHash: string;
	variantSchemaHash: string;
	sourceHash: string;
};

export const CODEGEN_HEADER_COMMENT = "// Generated by Trickroom. Do not edit.";
const CODEGEN_HEADER_PREFIX = "// trickroom-codegen: ";

const omitKeys = <T extends object>(value: T, keys: readonly string[]) =>
	Object.fromEntries(
		Object.entries(value).filter(([key]) => !keys.includes(key)),
	);

const mapValues = <T, U>(
	record: Record<string, T> | undefined,
	map: (value: T) => U,
): Record<string, U> =>
	Object.fromEntries(
		Object.entries(record ?? {}).map(([key, value]) => [key, map(value)]),
	);

/**
 * Hash over everything generation reads or a structural check would read.
 * Axis, value, slot and override target labels and history are dropped so
 * relabelling does not mark generated files stale; template node `name` and
 * `text` stay because they are part of the template the check compares.
 * Design-only subtrees are dropped from the template and from slot default
 * children (slots hosted inside one are dropped whole), so edits there never
 * mark generated files stale.
 */
export function hashCodegenSource(
	payload: Pick<
		SystemComponentDraftPayload,
		"root" | "slots" | "variants" | "overrideTargets"
	>,
): string {
	const designOnlyHosts = collectDesignOnlyPaths({ root: payload.root });
	const codeSlots = Object.fromEntries(
		Object.entries(payload.slots ?? {}).filter(
			([, slot]) => !designOnlyHosts.has(slot.hostPath),
		),
	);
	const input = stableStringify({
		root: stripDesignOnlyNodes(payload.root),
		slots: mapValues(codeSlots, (slot) => {
			const hashed = omitKeys(slot, ["label", "history"]);
			return slot.defaultChildren
				? {
						...hashed,
						defaultChildren: slot.defaultChildren
							.map(stripDesignOnlyNodes)
							.filter((child) => child !== null),
					}
				: hashed;
		}),
		variants: {
			...payload.variants,
			axes: mapValues(payload.variants?.axes, (axis) => ({
				...omitKeys(axis, ["label"]),
				values: mapValues(axis.values, (value) => omitKeys(value, ["label"])),
			})),
		},
		overrideTargets: mapValues(payload.overrideTargets, (target) =>
			omitKeys(target, ["label", "history"]),
		),
	});
	return `sha256:${sha256Hex(input)}`;
}

export function formatCodegenHeader(header: CodegenHeader): string {
	// Fixed key order so the header line is byte-stable.
	const ordered: CodegenHeader = {
		version: header.version,
		systemId: header.systemId,
		componentId: header.componentId,
		slug: header.slug,
		source: header.source,
		publishedVersion: header.publishedVersion,
		templateHash: header.templateHash,
		variantSchemaHash: header.variantSchemaHash,
		sourceHash: header.sourceHash,
	};
	return `${CODEGEN_HEADER_COMMENT}\n${CODEGEN_HEADER_PREFIX}${JSON.stringify(ordered)}`;
}

const isString = (value: unknown): value is string => typeof value === "string";

/** The header of a generated file, or null when it has no valid Trickroom header. */
export function parseCodegenHeader(contents: string): CodegenHeader | null {
	const [first, second] = contents.split(/\r?\n/u, 2);
	if (
		first !== CODEGEN_HEADER_COMMENT ||
		!second?.startsWith(CODEGEN_HEADER_PREFIX)
	) {
		return null;
	}

	let parsed: unknown;
	try {
		parsed = JSON.parse(second.slice(CODEGEN_HEADER_PREFIX.length));
	} catch {
		return null;
	}
	if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
		return null;
	}

	const value = parsed as Record<string, unknown>;
	if (
		value.version !== 1 ||
		!isString(value.systemId) ||
		!isString(value.componentId) ||
		!isString(value.slug) ||
		(value.source !== "published" && value.source !== "draft") ||
		!(value.publishedVersion === null || isString(value.publishedVersion)) ||
		!isString(value.templateHash) ||
		!isString(value.variantSchemaHash) ||
		!isString(value.sourceHash)
	) {
		return null;
	}

	return {
		version: 1,
		systemId: value.systemId,
		componentId: value.componentId,
		slug: value.slug,
		source: value.source,
		publishedVersion: value.publishedVersion,
		templateHash: value.templateHash,
		variantSchemaHash: value.variantSchemaHash,
		sourceHash: value.sourceHash,
	};
}
