export type SystemComponentManifestDiagnosticSeverity = "error" | "warning";

export type SystemComponentManifestDiagnosticCode =
	| "DUPLICATE_COMPONENT_SLUG"
	| "INVALID_COMPONENT_ID"
	| "INVALID_COMPONENT_SLUG"
	| "INVALID_CURRENT_VERSION"
	| "INVALID_MIGRATION_HINT_REFERENCE"
	| "INVALID_OVERRIDE_TARGET_PATH"
	| "INVALID_OVERRIDE_TARGET_ID"
	| "INVALID_OVERRIDE_TARGET_CAPABILITY"
	| "INVALID_PUBLISHED_VERSION_SHAPE"
	| "INVALID_SLOT_DEFINITION"
	| "INVALID_SLOT_HOST_PATH"
	| "INVALID_TEMPLATE_PATH"
	| "INVALID_TEMPLATE_ROOT"
	| "INVALID_VARIANT_CLASS_TARGET_PATH"
	| "INVALID_VARIANT_DEFAULT_VALUE"
	| "COMPOUND_EMPTY_WHEN"
	| "COMPOUND_ARRAY_VALUE"
	| "COMPOUND_INSUFFICIENT_CONDITIONS"
	| "COMPOUND_UNKNOWN_AXIS"
	| "COMPOUND_UNKNOWN_VALUE"
	| "COMPOUND_DUPLICATE_SIGNATURE"
	| "COMPOUND_EMPTY_CLASSES_BY_PATH"
	| "MISMATCHED_PUBLISHED_HASH"
	| "NON_ROOT_TEMPLATE_PATH"
	| "UNCONVENTIONAL_ROOT_PATH";

export type SystemComponentManifestDiagnostic = {
	code: SystemComponentManifestDiagnosticCode;
	severity: SystemComponentManifestDiagnosticSeverity;
	message: string;
	componentId?: string;
	path?: string;
};
