import { writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import { loadTailwindDesignSystem } from "../src/utils/tailwind-design-system.ts";
import {
	extractTailwindTokens,
	TAILWIND_TOKEN_DOMAIN_NAMESPACES,
	TAILWIND_TOKEN_DOMAINS,
} from "../src/utils/tailwind-token-domains.ts";

const require = createRequire(import.meta.url);
const projectRoot = process.cwd();
const tailwindCssPath = require.resolve("tailwindcss/index.css");
const tailwindPackageJson = require("tailwindcss/package.json") as {
	version: string;
};
const outputPath = path.join(
	projectRoot,
	"src",
	"utils",
	"default-tailwind-tokens.ts",
);

const { designSystem } = await loadTailwindDesignSystem({
	projectRoot,
	cssPath: path.relative(projectRoot, tailwindCssPath),
});
const tokensByDomain = extractTailwindTokens(designSystem);
const colorTokens = tokensByDomain.color;

const contents = `// Generated by scripts/generate-tailwind-tokens.ts.
// Tailwind CSS ${tailwindPackageJson.version}

export const defaultTailwindColorTokensVersion = "${tailwindPackageJson.version}";
export const defaultTailwindTokensVersion = "${tailwindPackageJson.version}";

export const defaultTailwindTokenDomainNamespaces = ${JSON.stringify(TAILWIND_TOKEN_DOMAIN_NAMESPACES, null, "\t")} as const;

export const defaultTailwindColorTokens = ${JSON.stringify(colorTokens, null, "\t")} as const;

export const defaultTailwindTokensByDomain = ${JSON.stringify(tokensByDomain, null, "\t")} as const;

export const defaultTailwindFontTokens = defaultTailwindTokensByDomain.font;

export type DefaultTailwindColorTokenName =
\tkeyof typeof defaultTailwindColorTokens;

export type DefaultTailwindFontTokenName = keyof typeof defaultTailwindFontTokens;

export type DefaultTailwindTokenDomain =
\tkeyof typeof defaultTailwindTokensByDomain;
`;

await writeFile(outputPath, contents, "utf8");
console.log(
	`Generated ${TAILWIND_TOKEN_DOMAINS.map((domain) => `${Object.keys(tokensByDomain[domain]).length} ${domain}`).join(", ")} Tailwind tokens at ${path.relative(projectRoot, outputPath)}`,
);
