import { writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import { loadTailwindDesignSystem } from "../src/utils/tailwind-design-system.ts";

const require = createRequire(import.meta.url);
const projectRoot = process.cwd();
const tailwindCssPath = require.resolve("tailwindcss/index.css");
const tailwindPackageJson = require("tailwindcss/package.json") as {
	version: string;
};
const outputPath = path.join(
	projectRoot,
	"src",
	"utils",
	"default-tailwind-tokens.ts",
);

const { designSystem } = await loadTailwindDesignSystem({
	projectRoot,
	cssPath: path.relative(projectRoot, tailwindCssPath),
});
const colorTokens = Object.fromEntries(
	designSystem.theme.namespace("--color").entries(),
);

const contents = `// Generated by scripts/generate-tailwind-tokens.ts.
// Tailwind CSS ${tailwindPackageJson.version}

export const defaultTailwindColorTokensVersion = "${tailwindPackageJson.version}";

export const defaultTailwindColorTokens = ${JSON.stringify(colorTokens, null, "\t")} as const;

export type DefaultTailwindColorTokenName =
\tkeyof typeof defaultTailwindColorTokens;
`;

await writeFile(outputPath, contents, "utf8");
console.log(
	`Generated ${Object.keys(colorTokens).length} Tailwind tokens at ${path.relative(projectRoot, outputPath)}`,
);
